import { uniqueId } from "lodash";

export const data = [
  {
    id: String(uniqueId()),
    title: "제목",
    contents: "아티스트 이름",
    isShowTime: false,
    category: { id: String(1), name: "노래" },
    boardAddress: {
      address: "서울 구로구",
      address_city: "서울",
      address_district: "구로구",
      lat: 127,
      lng: 32,
    },
    day: "",
    start_time: "",
    end_time: "",
    createAt: "",
    artist: {
      pick_user: [{}],
      id: "a",
      description: "",
      promotion_url: "",
      active_name: "",
    },
  },
  {
    id: String(uniqueId()),
    title: "제목",
    contents: "아티스트 이름",
    isShowTime: false,
    category: { id: String(4), name: "악기" },
    boardAddress: {
      address_city: "울산광역시",
      address_district: "남구",
      lat: 127,
      lng: 32,
    },
    day: "",
    start_time: "",
    end_time: "",
    createAt: "",
    artist: {
      pick_user: [{}],
      id: "a",
      description: "",
      promotion_url: "",
      active_name: "",
    },
  },
  {
    id: String(uniqueId()),
    title: "제목",
    contents: "아티스트 이름",
    isShowTime: false,
    category: { id: String(1), name: "노래" },
    boardAddress: {
      address_city: "울산광역시",
      address_district: "남구",
      lat: 127,
      lng: 32,
    },
    day: "",
    start_time: "",
    end_time: "",
    createAt: "",
    artist: {
      pick_user: [{}],
      id: "a",
      description: "",
      promotion_url: "",
      active_name: "",
    },
  },
  {
    id: String(uniqueId()),
    title: "제목",
    contents: "아티스트 이름",
    isShowTime: false,
    category: { id: String(1), name: "노래" },
    boardAddress: {
      address_city: "울산광역시",
      address_district: "남구",
      lat: 127,
      lng: 32,
    },
    day: "",
    start_time: "",
    end_time: "",
    createAt: "",
    artist: {
      pick_user: [{}],
      id: "a",
      description: "",
      promotion_url: "",
      active_name: "",
    },
  },
  {
    id: String(uniqueId()),
    title: "제목",
    contents: "아티스트 이름",
    isShowTime: false,
    category: { id: String(2), name: "춤" },
    boardAddress: {
      address_city: "울산광역시",
      address_district: "남구",
      lat: 127,
      lng: 32,
    },
    day: "",
    start_time: "",
    end_time: "",
    createAt: "",
    artist: {
      pick_user: [{}],
      id: "a",
      description: "",
      promotion_url: "",
      active_name: "",
    },
  },
  {
    id: String(uniqueId()),
    title: "제목",
    contents: "아티스트 이름",
    isShowTime: false,
    category: { id: String(4), name: "악기" },
    boardAddress: {
      address_city: "울산광역시",
      address_district: "남구",
      lat: 127,
      lng: 32,
    },
    day: "",
    start_time: "",
    end_time: "",
    createAt: "",
    artist: {
      pick_user: [{}],
      id: "a",
      description: "",
      promotion_url: "",
      active_name: "",
    },
  },
  {
    id: String(uniqueId()),
    title: "제목",
    contents: "아티스트 이름",
    isShowTime: false,
    category: { id: String(1), name: "노래" },
    boardAddress: {
      address_city: "울산광역시",
      address_district: "남구",
      lat: 127,
      lng: 32,
    },
    day: "",
    start_time: "",
    end_time: "",
    createAt: "",
    artist: {
      pick_user: [{}],
      id: "a",
      description: "",
      promotion_url: "",
      active_name: "",
    },
  },
  {
    id: String(uniqueId()),
    title: "제목",
    contents: "아티스트 이름",
    isShowTime: false,
    category: { id: String(1), name: "노래" },
    boardAddress: {
      address_city: "울산광역시",
      address_district: "남구",
      lat: 127,
      lng: 32,
    },
    day: "",
    start_time: "",
    end_time: "",
    createAt: "",
    artist: {
      pick_user: [{}],
      id: "a",
      description: "",
      promotion_url: "",
      active_name: "",
    },
  },
  {
    id: String(uniqueId()),
    title: "제목",
    contents: "아티스트 이름",
    isShowTime: false,
    category: { id: String(1), name: "노래" },
    boardAddress: {
      address_city: "울산광역시",
      address_district: "남구",
      lat: 127,
      lng: 32,
    },
    day: "",
    start_time: "",
    end_time: "",
    createAt: "",
    artist: {
      pick_user: [{}],
      id: "a",
      description: "",
      promotion_url: "",
      active_name: "",
    },
  },
  {
    id: String(uniqueId()),
    title: "제목",
    contents: "아티스트 이름",
    isShowTime: false,
    category: { id: String(1), name: "노래" },
    boardAddress: {
      address_city: "울산광역시",
      address_district: "남구",
      lat: 127,
      lng: 32,
    },
    day: "",
    start_time: "",
    end_time: "",
    createAt: "",
    artist: {
      pick_user: [{}],
      id: "a",
      description: "",
      promotion_url: "",
      active_name: "",
    },
  },
  {
    id: String(uniqueId()),
    title: "제목",
    contents: "아티스트 이름",
    isShowTime: false,
    category: { id: String(2), name: "춤" },
    boardAddress: {
      address_city: "울산광역시",
      address_district: "남구",
      lat: 127,
      lng: 32,
    },
    day: "",
    start_time: "",
    end_time: "",
    createAt: "",
    artist: {
      pick_user: [{}],
      id: "a",
      description: "",
      promotion_url: "",
      active_name: "",
    },
  },
  {
    id: String(uniqueId()),
    title: "제목",
    contents: "아티스트 이름",
    isShowTime: false,
    category: { id: String(4), name: "악기" },
    boardAddress: {
      address_city: "울산광역시",
      address_district: "남구",
      lat: 127,
      lng: 32,
    },
    day: "",
    start_time: "",
    end_time: "",
    createAt: "",
    artist: {
      pick_user: [{}],
      id: "a",
      description: "",
      promotion_url: "",
      active_name: "",
    },
  },
  {
    id: String(uniqueId()),
    title: "제목",
    contents: "아티스트 이름",
    isShowTime: false,
    category: { id: String(1), name: "노래" },
    boardAddress: {
      address_city: "울산광역시",
      address_district: "남구",
      lat: 127,
      lng: 32,
    },
    day: "",
    start_time: "",
    end_time: "",
    createAt: "",
    artist: {
      pick_user: [{}],
      id: "a",
      description: "",
      promotion_url: "",
      active_name: "",
    },
  },
  {
    id: String(uniqueId()),
    title: "제목",
    contents: "아티스트 이름",
    isShowTime: false,
    category: { id: String(3), name: "몰라" },
    boardAddress: {
      address_city: "울산광역시",
      address_district: "남구",
      lat: 127,
      lng: 32,
    },
    day: "",
    start_time: "",
    end_time: "",
    createAt: "",
    artist: {
      pick_user: [{}],
      id: "a",
      description: "",
      promotion_url: "",
      active_name: "",
    },
  },
  {
    id: String(uniqueId()),
    title: "제목",
    contents: "아티스트 이름",
    isShowTime: false,
    category: { id: String(1), name: "노래" },
    boardAddress: {
      address_city: "울산광역시",
      address_district: "남구",
      lat: 127,
      lng: 32,
    },
    day: "",
    start_time: "",
    end_time: "",
    createAt: "",
    artist: {
      pick_user: [{}],
      id: "a",
      description: "",
      promotion_url: "",
      active_name: "",
    },
  },
  {
    id: String(uniqueId()),
    title: "제목",
    contents: "아티스트 이름",
    isShowTime: false,
    category: { id: String(1), name: "노래" },
    boardAddress: {
      address_city: "울산광역시",
      address_district: "남구",
      lat: 127,
      lng: 32,
    },
    day: "",
    start_time: "",
    end_time: "",
    createAt: "",
    artist: {
      pick_user: [{}],
      id: "a",
      description: "",
      promotion_url: "",
      active_name: "",
    },
  },
  {
    id: String(uniqueId()),
    title: "제목",
    contents: "아티스트 이름",
    isShowTime: false,
    category: { id: String(1), name: "노래" },
    boardAddress: {
      address_city: "울산광역시",
      address_district: "남구",
      lat: 127,
      lng: 32,
    },
    day: "",
    start_time: "",
    end_time: "",
    createAt: "",
    artist: {
      pick_user: [{}],
      id: "a",
      description: "",
      promotion_url: "",
      active_name: "",
    },
  },
  {
    id: String(uniqueId()),
    title: "제목",
    contents: "아티스트 이름",
    isShowTime: false,
    category: { id: String(4), name: "악기" },
    boardAddress: {
      address_city: "울산광역시",
      address_district: "남구",
      lat: 127,
      lng: 32,
    },
    day: "",
    start_time: "",
    end_time: "",
    createAt: "",
    artist: {
      pick_user: [{}],
      id: "a",
      description: "",
      promotion_url: "",
      active_name: "",
    },
  },
  {
    id: String(uniqueId()),
    title: "제목",
    contents: "아티스트 이름",
    isShowTime: false,
    category: { id: String(3), name: "몰라" },
    boardAddress: {
      address_city: "울산광역시",
      address_district: "남구",
      lat: 127,
      lng: 32,
    },
    day: "",
    start_time: "",
    end_time: "",
    createAt: "",
    artist: {
      pick_user: [{}],
      id: "a",
      description: "",
      promotion_url: "",
      active_name: "",
    },
  },
  {
    id: String(uniqueId()),
    title: "제목",
    contents: "아티스트 이름",
    isShowTime: false,
    category: { id: String(1), name: "노래" },
    boardAddress: {
      address_city: "울산광역시",
      address_district: "남구",
      lat: 127,
      lng: 32,
    },
    day: "",
    start_time: "",
    end_time: "",
    createAt: "",
    artist: {
      pick_user: [{}],
      id: "a",
      description: "",
      promotion_url: "",
      active_name: "",
    },
  },
  {
    id: String(uniqueId()),
    title: "제목",
    contents: "아티스트 이름",
    isShowTime: false,
    category: { id: String(1), name: "노래" },
    boardAddress: {
      address_city: "울산광역시",
      address_district: "남구",
      lat: 127,
      lng: 32,
    },
    day: "",
    start_time: "",
    end_time: "",
    createAt: "",
    artist: {
      pick_user: [{}],
      id: "a",
      description: "",
      promotion_url: "",
      active_name: "",
    },
  },
  {
    id: String(uniqueId()),
    title: "제목",
    contents: "아티스트 이름",
    isShowTime: false,
    category: { id: String(1), name: "노래" },
    boardAddress: {
      address_city: "울산광역시",
      address_district: "남구",
      lat: 127,
      lng: 32,
    },
    day: "",
    start_time: "",
    end_time: "",
    createAt: "",
    artist: {
      pick_user: [{}],
      id: "a",
      description: "",
      promotion_url: "",
      active_name: "",
    },
  },
  {
    id: String(uniqueId()),
    title: "제목",
    contents: "아티스트 이름",
    isShowTime: false,
    category: { id: String(1), name: "노래" },
    boardAddress: {
      address_city: "울산광역시",
      address_district: "남구",
      lat: 127,
      lng: 32,
    },
    day: "",
    start_time: "",
    end_time: "",
    createAt: "",
    artist: {
      pick_user: [{}],
      id: "a",
      description: "",
      promotion_url: "",
      active_name: "",
    },
  },
  {
    id: String(uniqueId()),
    title: "제목",
    contents: "아티스트 이름",
    isShowTime: false,
    category: { id: String(2), name: "춤" },
    boardAddress: {
      address_city: "울산광역시",
      address_district: "남구",
      lat: 127,
      lng: 32,
    },
    day: "",
    start_time: "",
    end_time: "",
    createAt: "",
    artist: {
      pick_user: [{}],
      id: "a",
      description: "",
      promotion_url: "",
      active_name: "",
    },
  },
  {
    id: String(uniqueId()),
    title: "제목",
    contents: "아티스트 이름",
    isShowTime: false,
    category: { id: String(2), name: "춤" },
    boardAddress: {
      address_city: "울산광역시",
      address_district: "남구",
      lat: 127,
      lng: 32,
    },
    day: "",
    start_time: "",
    end_time: "",
    createAt: "",
    artist: {
      pick_user: [{}],
      id: "a",
      description: "",
      promotion_url: "",
      active_name: "",
    },
  },
  {
    id: String(uniqueId()),
    title: "제목",
    contents: "아티스트 이름",
    isShowTime: false,
    category: { id: String(2), name: "춤" },
    boardAddress: {
      address_city: "울산광역시",
      address_district: "남구",
      lat: 127,
      lng: 32,
    },
    day: "",
    start_time: "",
    end_time: "",
    createAt: "",
    artist: {
      pick_user: [{}],
      id: "a",
      description: "",
      promotion_url: "",
      active_name: "",
    },
  },
  {
    id: String(uniqueId()),
    title: "제목",
    contents: "아티스트 이름",
    isShowTime: false,
    category: { id: String(4), name: "악기" },
    boardAddress: {
      address_city: "울산광역시",
      address_district: "남구",
      lat: 127,
      lng: 32,
    },
    day: "",
    start_time: "",
    end_time: "",
    createAt: "",
    artist: {
      pick_user: [{}],
      id: "a",
      description: "",
      promotion_url: "",
      active_name: "",
    },
  },
  {
    id: String(uniqueId()),
    title: "제목",
    contents: "아티스트 이름",
    isShowTime: false,
    category: { id: String(3), name: "몰라" },
    boardAddress: {
      address_city: "울산광역시",
      address_district: "남구",
      lat: 127,
      lng: 32,
    },
    day: "",
    start_time: "",
    end_time: "",
    createAt: "",
    artist: {
      pick_user: [{}],
      id: "a",
      description: "",
      promotion_url: "",
      active_name: "",
    },
  },
  {
    id: String(uniqueId()),
    title: "제목",
    contents: "아티스트 이름",
    isShowTime: false,
    category: { id: String(3), name: "몰라" },
    boardAddress: {
      address_city: "울산광역시",
      address_district: "남구",
      lat: 127,
      lng: 32,
    },
    day: "",
    start_time: "",
    end_time: "",
    createAt: "",
    artist: {
      pick_user: [{}],
      id: "a",
      description: "",
      promotion_url: "",
      active_name: "",
    },
  },
  {
    id: String(uniqueId()),
    title: "제목",
    contents: "아티스트 이름",
    isShowTime: false,
    category: { id: String(2), name: "춤" },
    boardAddress: {
      address_city: "울산광역시",
      address_district: "남구",
      lat: 127,
      lng: 32,
    },
    day: "",
    start_time: "",
    end_time: "",
    createAt: "",
    artist: {
      pick_user: [{}],
      id: "a",
      description: "",
      promotion_url: "",
      active_name: "",
    },
  },
  {
    id: String(uniqueId()),
    title: "제목",
    contents: "아티스트 이름",
    isShowTime: false,
    category: { id: String(4), name: "악기" },
    boardAddress: {
      address_city: "울산광역시",
      address_district: "남구",
      lat: 127,
      lng: 32,
    },
    day: "",
    start_time: "",
    end_time: "",
    createAt: "",
    artist: {
      pick_user: [{}],
      id: "a",
      description: "",
      promotion_url: "",
      active_name: "",
    },
  },
  {
    id: String(uniqueId()),
    title: "제목",
    contents: "아티스트 이름",
    isShowTime: false,
    category: { id: String(3), name: "몰라" },
    boardAddress: {
      address_city: "울산광역시",
      address_district: "남구",
      lat: 127,
      lng: 32,
    },
    day: "",
    start_time: "",
    end_time: "",
    createAt: "",
    artist: {
      pick_user: [{}],
      id: "a",
      description: "",
      promotion_url: "",
      active_name: "",
    },
  },
];
